[project]
name = "azure-storage-fuse"
version = "2.4.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpie>=3.2.4",
    "nvchecker>=2.16",
]
